name: "Bi Review"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches: [main]

env:
  AWS_ACCOUNT_ID: "588738614703"
  AWS_REGION: "us-east-1"
  AWS_ROLE_TO_ASSUME: "GitHubActionOidcRole"
  CPPCHECK_MISRA_RESULT_XML_FILE: "cppcheck-misra"
  SCRIPTS_PATH: ".github/workflows/scripts"

jobs:
  trigger_bi_review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      pages: write
    steps:
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: '${{ github.repositoryUrl }}'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_TO_ASSUME }}
